// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Preloader from "@/components/Preloader";  

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         <Preloader />          
//         <div className="w-full">
//           {children}
//         </div>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import Preloader from "@/components/Preloader";  


// Update these with your actual domain and brand information
const siteName = "QUICKART";
const siteUrl = "https://yourdomain.com"; // Replace with your actual domain
const siteDescription = "Discover timeless elegance at LUXE - premium fashion for the modern individual. Shop curated collections of menswear, womenswear, and accessories crafted with sustainable luxury.";
const siteKeywords = "luxury fashion, premium clothing, designer wear, sustainable fashion, men's collection, women's collection, luxury accessories, LUXE brand";

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: "QUICKART - Premium Luxury Fashion Brand",
    template: "%s | QUICKART"
  },
  description: siteDescription,
  keywords: siteKeywords,
  authors: [{ name: "QUICKART", url: siteUrl }],
  creator: "QUICKART",
  publisher: "QUICKART",
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  
  // Open Graph metadata for social media sharing (Facebook, LinkedIn, etc.)
  openGraph: {
    title: "QUICKART - Premium Quickart Fashion Brand",
    description: siteDescription,
    url: siteUrl,
    siteName: siteName,
    images: [
      {
        url: "/og-image.jpg", // Create and add an OG image to your public folder
        width: 1200,
        height: 630,
        alt: "QUICKART - Quickart Fashion Brand",
      },
    ],
    locale: "en_US",
    type: "website",
  },
  
  // Twitter Card metadata
  twitter: {
    card: "summary_large_image",
    title: "LUXE - Premium Quickart Fashion Brand",
    description: siteDescription,
    images: ["/twitter-image.jpg"], // Create and add a Twitter-specific image (1200x600)
    site: "@luxe", // Replace with your Twitter handle
    creator: "@luxe", // Replace with your Twitter handle
  },
  
  // Icons
  icons: {
    icon: [
      { url: "/favicon.ico", sizes: "any" },
      { url: "/icon.png", type: "image/png", sizes: "32x32" },
    ],
    apple: [{ url: "/apple-icon.png", sizes: "180x180", type: "image/png" }],
    other: [
      {
        rel: "mask-icon",
        url: "/safari-pinned-tab.svg",
        color: "#800000", // Your maroon color
      },
    ],
  },
  
  // Manifest for PWA
  manifest: "/manifest.json",
  
  // Robots
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  
  // Verification (Add your verification codes)
  verification: {
    google: "your-google-verification-code", // Add your Google Search Console verification
    // yandex: "your-yandex-verification-code",
    // me: "your-email@example.com",
  },
  
  // Alternates (for multilingual sites)
  alternates: {
    canonical: siteUrl,
    // languages: {
    //   'en-US': '/en-US',
    //   'es-ES': '/es-ES',
    // },
  },
  
  // Category
  category: "fashion",
  
  // App links (for mobile apps)
  appLinks: {
    ios: {
      url: "https://apps.apple.com/app/your-app-id",
      app_store_id: "your-app-store-id",
    },
    android: {
      package: "com.luxe.app",
      url: "https://play.google.com/store/apps/details?id=com.luxe.app",
    },
  },
  
  // Apple web app
  appleWebApp: {
    title: "QUICKART",
    statusBarStyle: "black-translucent",
    capable: true,
  },
  
  // Other
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
    userScalable: true,
  },
  colorScheme: "light",
  themeColor: "#800000", // Your maroon color
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Preconnect to external resources for performance */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        
        {/* Add JSON-LD structured data for better SEO */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "QUICKART",
              "url": siteUrl,
              "logo": `${siteUrl}/logo.png`,
              "sameAs": [
                "https://www.instagram.com/luxe/",
                "https://www.facebook.com/luxe/",
                "https://twitter.com/luxe",
                "https://www.pinterest.com/luxe/"
              ],
              "description": siteDescription,
              "address": {
                "@type": "PostalAddress",
                "streetAddress": "123 Luxury Avenue",
                "addressLocality": "New York",
                "addressRegion": "NY",
                "postalCode": "10005",
                "addressCountry": "US"
              },
              "contactPoint": {
                "@type": "ContactPoint",
                "telephone": "+1-212-555-0123",
                "contactType": "customer service",
                "availableLanguage": ["English"]
              }
            })
          }}
        />
        
        {/* Add e-commerce structured data if applicable */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "url": siteUrl,
              "name": "LUXE",
              "description": siteDescription,
              "potentialAction": {
                "@type": "SearchAction",
                "target": `${siteUrl}/search?q={search_term_string}`,
                "query-input": "required name=search_term_string"
              }
            })
          }}
        />
      </head>
      <body
        className="antialiased"
      >
        <Preloader />          
        <div className="w-full">
          {children}
        </div>
      </body>
    </html>
  );
}